### ISSUE TITLE
Setting the bodyHtmlBegin property breaks the page functionality

### ISSUE THREAD

**Issue by amumufun** [vikejs/vike-vue#146] opened 2024-07-19 09:41 UTC
### Description

import vikeVue from "vike-vue/config";
import type { Config } from "vike/types";
import Head from "../layouts/HeadDefault.vue";
import Layout from "../layouts/LayoutDefault.vue";

// Default config (can be overridden by pages)
export default {
  Layout,
  Head,
  // <title>
  //# BATI.has("auth0") || BATI.has("firebase-auth") || BATI.has("authjs")
  passToClient: ["user"],
  title: "My Vike App",
  extends: vikeVue,
  stream: "web",
  bodyHtmlEnd: '<div class="test">1111111</div>',
} satisfies Config;

After switching pages, all clicking and other functions became invalid
[my-app.zip](https://github.com/user-attachments/files/16310247/my-app.zip)

**Comment by brillout** [comment] 2024-07-19 09:47
It should be valid HTML.

**Comment by brillout** [comment] 2024-07-19 09:49
Hm, actually it is valid HTML.

**Comment by brillout** [comment] 2024-07-19 09:49
Can you publish the reproduction on GitHub?

**Comment by amumufun** [comment] 2024-07-19 09:56
bodyHtmlEnd: \'\<div class=\"test\"\>1111111\<\/div\>\',

git@github.com:amumufun/my-app.git

**Comment by brillout** [comment] 2024-07-19 11:40
Indeed I could reproduce, let me have a look.

**Comment by brillout** [comment] 2024-07-19 12:22
[Fix](https://github.com/vikejs/vike-vue/pull/147) pre-released as `0.7.6-commit-2067b0b`.

The fix isn't completely finished, (I'll finish it later) but it should work already.

**Comment by pdanpdan** [comment] 2024-07-19 12:25
:)
Now can we also default to empty `bodyHtml{Begin,End}`

**Comment by brillout** [comment] 2024-07-19 12:31
:)
FYI the reason I was pushing for manipulating the DOM was to enable Vike extensions to use that setting. But I've an alternative idea to make it work for Vike extensions, so I'm now quite happy to remove the whole DOM manipulating thing :)

> Now can we also default to empty `bodyHtml{Begin,End}`

WDYT of the following?

> > * now the default HTML has an extra element most people don't need, and that does not fit the needs of most people that use teleport - so basically now everyone needs to define a `bodyHtmlEnd()`
> 
> Indeed, but I don't think it can cause any real issue?
> 
> On the flip side it enables [this](https://vike.dev/bodyHtmlEnd#:~:text=Teleports%20work%20out%20of%20the%20box%20when%20using%20%3CTeleport%20to%3D%22teleported%22%3E%20and%20you%20don%27t%20have%20to%20use%20bodyHtml%7BBegin%2CEnd%7D%20then.), which seems like a nice thing to have? `` Teleports work out of the box when using `<Teleport to="teleported">` and you don't have to use `bodyHtml{Begin,End}` then. ``

Quoting from [here](https://github.com/vikejs/vike-vue/issues/87#issuecomment-2191102148).

I ain't that familiar with Vue and its teleports, so I could very well be wrong here.

**Comment by pdanpdan** [comment] 2024-07-19 12:37
Ok, I searched for `id="teleported"` on github and it looks like there are a few people using exactly the example from vue docs.
I didn't want to insist too much, sorry.

**Comment by brillout** [comment] 2024-07-19 12:39
So you agree we should keep the default then?

> I didn't want to insist too much, sorry.

No I like it :)

**Comment by pdanpdan** [comment] 2024-07-19 12:48
I think in the original implementation it was benign, but now from what I understand from [here](https://github.com/vikejs/vike-vue/blob/c6a36a022e9786372e94e0ead07ec667ce7c5165/packages/vike-vue/src/renderer/onRenderHtml.ts#L60) the default cannot be removed anymore.

So this if not benign anymore (you cannot use the `id="teleported"` in the page).

**Comment by brillout** [comment] 2024-07-19 13:17
Yes, it cannot be removed. But I don't see any practical downside to it?

**Comment by amumufun** [comment] 2024-07-20 02:34
I want to add some tracking scripts in bodyHtmlBegin, how should I write it

**Comment by brillout** [comment] 2024-07-20 11:11
@amumufun See https://github.com/vikejs/vike/commit/6ac539c4ed657633ed99c8749f6c2cd3faf4728d. As to which one to use, that depends on your use case. (Thank you for the personal sponsorship!)

**Comment by brillout** [comment] 2024-07-22 11:22
@pdanpdan Indeed a conflict with a library using the ID `teleported` could be an issue (although AFAICT it seems unlikely :thinking:), but we could solve it by adding a setting such as `bodyHtmlEnd: { default: false }`. I can't say whether the added convenience is worth it since I ain't that familiar with Vue. But the fact that Chris had the idea is a signal that it's at least somewhat useful.

> extra useless div in template 

AFAICT it's a negligible downside.

> At least something like `const bodyHtmlEndHooks = pageContext.config.bodyHtmlEnd ?? [defaultTeleport]` would be better (if `pageContext.config.bodyHtmlEnd` is not an empty array by default - else check for length)

We cannot do that because adding a Vike extension that uses `bodyHtmlEnd` would potentially break the app. In other words: `bodyHtmlEnd` needs to be cumulative.

**Closed** 2024-07-29 15:03 UTC
Labels: bug :boom:
